### ISSUE TITLE
how to get the demo running?

### ISSUE THREAD

**Issue by SoonyangZhang** [dariobanfi/multipath-sdn-controller#1]
Hi
I have already get the ovs-multipath installed. But when I run ./demo.py, It waning permission denied. Any help will be great appreciated.

**Comment by dariobanfi** [comment]
did you run `chmod +x demo.py` ?

**Comment by SoonyangZhang** [comment]
Yes. But there is other thing goes wrong. I should install mininet first.

**Comment by dariobanfi** [comment]
Yeah of course, you will need at least:
- Mininet
- To have installed the patched version of openvswitch
- vlc
- Python dependencies in demo.py

Sorry but I did this for my thesis a while ago and I didn't really make it "user-friendly" as I didn't think anybody would be interested :)

**Comment by dariobanfi** [comment]
ah and you need to run as root (as mininet requires it)

**Comment by SoonyangZhang** [comment]
Very appreciate your help. Did you install mininet or use the provided VM before? I will try install them again. If there are problems, I will put it later and hope to get your help.

**Comment by dariobanfi** [comment]
I used an ubuntu-server image and installed mininet there

**Comment by SoonyangZhang** [comment]
ok, It seems I get it running. But how can I see the video?  the url?

**Comment by dariobanfi** [comment]
Well you have to make sure there is actually a video.
Here you can insert a path to a video: https://github.com/dariobanfi/multipath-sdn-controller/blob/master/demo/demo.py#L26
As long as you have vlc installed it should open it automatically

**Comment by SoonyangZhang** [comment]
I have a file named vid.f4v.  When I run ./demo.py for a while, it seems disrupted.
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd udpbwtest 2> /dev/null
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old screen sessions
Traceback (most recent call last):
  File "/usr/bin/mn", line 280, in <module>
    MininetRunner()
  File "/usr/bin/mn", line 113, in __init__
    self.begin()
  File "/usr/bin/mn", line 218, in begin
    cleanup()
  File "/usr/lib/python2.7/dist-packages/mininet/clean.py", line 40, in cleanup
    cleanUpScreens()
  File "/usr/lib/python2.7/dist-packages/mininet/term.py", line 49, in cleanUpScreens
    output = quietRun( 'screen -ls' ).split( '\n' )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 117, in quietRun
    return errRun( cmd, stderr=STDOUT, **kwargs )[ 0 ]
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 77, in errRun
    popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by dariobanfi** [comment]
Any other error is thrown before that?

**Comment by SoonyangZhang** [comment]
Yes， it seems the ovs goes wrong. I installed mininet and then ovs-multipath.
Starting Demo
Starting controller
./configuration/start_controller.sh: line 3: ryu-manager: command not found
Creating network
ovs-vsctl: unix:/usr/local/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
ovs-vsctl exited with code 1
*** Error connecting to ovs-db with ovs-vsctl
Make sure that Open vSwitch is installed, that ovsdb-server is running, and that
"ovs-vsctl show" works correctly.
You may wish to try "service openvswitch-switch start".
Caught exception!  Cleaning up...

**Comment by SoonyangZhang** [comment]
It is the fault of ovs and I reinstalled the software.
Received Start Message
Starting Demo
Starting controller
./configuration/start_controller.sh: line 3: ryu-manager: command not found
Creating network
Unable to contact the remote controller at 127.0.0.1:6633
/bin/sh: 1: ./configuration/configure_singlepath.sh: Permission denied
Testing host reachability
src -> X 
dst -> X 
*** Results: 100% dropped (2/2 lost)
Step 1 - SinglePath Streaming
Step 2 - Starting Multipath controller
/bin/sh: 1: ./configuration/configure_controller_parameters.sh: Permission denied
^CCaught exception!  Cleaning up...
Traceback (most recent call last):
  File "./demo.py", line 122, in start
    sleep(30)
KeyboardInterrupt
Demo Cleanup
Killing VLC
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd udpbwtest 2> /dev/null
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old screen sessions
Traceback (most recent call last):
  File "/usr/bin/mn", line 280, in <module>
    MininetRunner()
  File "/usr/bin/mn", line 113, in __init__
    self.begin()
  File "/usr/bin/mn", line 218, in begin
    cleanup()
  File "/usr/lib/python2.7/dist-packages/mininet/clean.py", line 40, in cleanup
    cleanUpScreens()
  File "/usr/lib/python2.7/dist-packages/mininet/term.py", line 49, in cleanUpScreens
    output = quietRun( 'screen -ls' ).split( '\n' )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 117, in quietRun
    return errRun( cmd, stderr=STDOUT, **kwargs )[ 0 ]
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 77, in errRun
    popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Terminated

**Comment by dariobanfi** [comment]
Well you need to install ` ryu-manager`because it says `./configuration/start_controller.sh: line 3: ryu-manager: command not found`

And here `/bin/sh: 1: ./configuration/configure_singlepath.sh: Permission denied` you need to `chmod +x` it

**Comment by SoonyangZhang** [comment]
I  installed ryu-manager already. and it runs successfully.
But finally I cannot see the video scene.
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet
Traceback (most recent call last):
  File "/home/zsy/ovs/multipath-sdn-controller/controller/mpsdn_controller.py", line 341, in probe_packet_handler
    send_dpid = int(data[0])
ValueError: invalid literal for int() with base 10: ''
Unable to parse incoming probe packet


------------------
s[5] p[1] utilization 177 max_capacity 876000
s[5] p[2] utilization 177 max_capacity 25000000
s[5] p[3] utilization 60 max_capacity 25000000
s[2] p[1] utilization 161 max_capacity 25000000
s[2] p[2] utilization 153 max_capacity 876000


Demo Cleanup
Killing VLC
./configuration/start_controller.sh: line 3:  7436 Terminated              ryu-manager --observe-links ../controller/mpsdn_controller.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "./demo.py", line 176, in handle_websocket
    message = wsock.receive()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 301, in receive
    return self.read_message()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 270, in read_message
    self.handle_close(header, payload)
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 166, in handle_close
    code = struct.unpack('!H', payload[:2])[0]
error: unpack requires a string argument of length 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "./demo.py", line 176, in handle_websocket
    message = wsock.receive()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 301, in receive
    return self.read_message()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 270, in read_message
    self.handle_close(header, payload)
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/websocket.py", line 166, in handle_close
    code = struct.unpack('!H', payload[:2])[0]
error: unpack requires a string argument of length 2

**Comment by dariobanfi** [comment]
I'll try to run it myself this weekend again and try to help you, sorry but for now I don't have the time.

**Comment by SoonyangZhang** [comment]
Very thankful your help. It may waste you precious time. So, you don't have to. I am just curious about the part of multi-path transmission. You know,it  gets quite attention in the area of networking. In fact, I do not know Python. If I do, I can know the detail of the code and I think I can make it running. So first, it would be better for me to learn some Python. So very thanks to your kind heart.
